### ISSUE TITLE
Issue with .qmd render

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw-01-SwethaSiripurapu#1]
Hi Swetha, 

It looks like there's an unrecognized package in the `data()` function. This prevents the autograder from rendering the html. 

```
Quitting from lines 238-286 [unnamed-chunk-8] (hw-01.qmd)
Error in `find.package()`:
! there is no package called 'HistData'
Backtrace:
 1. utils::data(Minard.troops, package = "HistData")
 2. base::find.package(package, lib.loc, verbose = verbose)
Execution halted
```

If there's a specific package this this data is being drawn from, I would put this in the place of `"HistData"`, push the changes, and the autograder will run again.

**Comment by SwethaSiripurapuu** [comment]
hello professor, 

I have downloaded histdata from install.packages("histdata).  Is there something i am missing?

<img width="311" alt="image" src="https://github.com/INFO526-DataViz/hw-01-SwethaSiripurapu/assets/123128520/65d7952d-0c7b-42d1-bc29-fa9b3157646a">

**Comment by SwethaSiripurapuu** [comment]
Hello Professor,

The auto grader has passed all the checks. Thanks
