### ISSUE TITLE
Homework 1 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/hw-01-SwethaSiripurapu#2]
Dear Swetha -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

---

### Exercise 1: `[10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: Good work!

### Exercise 2: `[20 / 20 points]`

a. `[8 / 8 points]`

  - Histogram: `[3 / 3]`
  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: Good work. I however would like to see you practice using `ggplot2` since you will have more power over your visuals in the long run. I usually only use base plots to quickly check a distribution or property of the data.

- [x] Resolved
Additional feedback: I recommend keeping the recommended bin width. I would also like to see larger text labels - e.g., `theme_minimal(base_size = 14)`. Next time, you should use formatting instead of "=>" to highlight sections. 

b. `[5 / 5 points]`

  - Boxplot: `[3 / 3]`
  - Narrative: `[2 / 2]`
  - Feedback: Good work. The only issue is that the legend title needs to be capitalized. 

- [x] Resolved
Additional feedback: I think there was a miscommunication, I meant the legend should be "Division". You resolved the issue however. 

c. `[2 / 2 points]`

  - Feedback: Your reasoning is correct, but remember that lower data-to-ink ratio does not directly translate to a more effective and readable plot. I agree with removing the legend, but not the color.

- [x] Resolved

d. `[5 / 5 points]`

  - Time series plot: `[3 / 3]`
  - Narrative: `[2/ 2]`
  - Feedback: Good work!

### Exercise 3: `[20 / 20 points]`

a. `[2 / 2]`
  - Feedback: Correct.

b. `[2 / 2]`
  - Feedback: Correct.

c. `[16 / 16]` (2 points each)
  - Feedback: Good work, but I suggest using `grid.arrange()` from the [`gridExtra`](https://cran.r-project.org/web/packages/gridExtra/vignettes/arrangeGrob.html) package to arrange each set of plots the way I did in the original question. 
- [x] Resolved
  
### Exercise 4: `[10 / 10 points]`

- Plot: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: I agree with your approach, but your y-axes are cut off too short.

- [x] Resolved (but see feedback)
Additional feedback: I see that you tried to address the feedback, however now the opposite issue is occurring. I recommend just using `ylim()` in the future to slightly increase the y-axis limit.

### Exercise 5: `[20 / 20 points]`

- Feedback: You produced the correct plot, but your use of color makes it difficult to read. Less is more in this case. Your legends are also not in an ideal area. Lastly, the render size cuts off some labels.

- [x] Resolved

### Overall: `[20 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
 Feedback: 4/5 of your document was the readout of the accidents data. I recommend using `glimpse()` or `head()`. 
- [x] Resolved

- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
 Feedback: It is not clear what your commit messages are addressing. I suggest more frequent and specific messages. 

- [x] Resolved

Additional feedback: keep the original feedback in mind for next time. I will be more strict in the next grading session. 

- `[3 / 3]` - Reasonably sized figures.
 Feedback: There was some issues with labels being cut off. 
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by SwethaSiripurapuu** [comment]
Hello Professor, I have implemented the changes and updated the code accordingly. Thank you for your feedback.

**Comment by Gchism94** [comment]
Good work on the resubmission. I gave some additional feedback, but you now received full credit.

**Comment by SwethaSiripurapuu** [comment]
Hello Professor, I am unable to see the feedback on my resubmission. Am I missing something?

**Comment by Gchism94** [comment]
It looks like it didn't save. I'll go through it again later, but you have full credit either way.

**Comment by Gchism94** [comment]
Your feedback is now there.

**Comment by SwethaSiripurapuu** [comment]
Thank you professor
